### ISSUE TITLE
injecting blocker results in error after update

### ISSUE THREAD

**Issue by jhung-dev** [OpenByteDev/burnt-sushi#10] opened 2023-07-17 04:56 UTC
running burnt-sushi as an executable path in elevated Command Prompt gives verbose errors. 
everything up to injecting the actual dll is fine, and then the program terminates. 

---full console log file below (note: user-dependent paths have been substituted with their appropriate environment variables)---

C:\Windows\System32>"%HOMEPATH%\Downloads\BurntSushi.exe"

C:\Windows\System32>[DEBUG] Attached to console
[INFO] BurntSushi v0.2.0
[INFO] Looking for Spotify...
[INFO] Found Spotify (PID=26072)
[INFO] Loading filter config...
[DEBUG] Looking for filter config according to cli args...
[DEBUG] Looking for filter config next to executable...
[DEBUG] Looking for filter config at '%HOMEPATH%\Downloads\filter.toml'
[DEBUG] Loading default filter config...
[INFO] Preparing blocker...
[DEBUG] Looking for blocker according to cli args...
[DEBUG] Looking for blocker next to executable...
[DEBUG] Looking for blocker at '%HOMEPATH%\Downloads\BurntSushiBlocker_x86.dll'
[DEBUG] Looking for existing blocker in temporary directory...
[DEBUG] Looking for blocker at '%APPDATA%\Local\OpenByteDev\BurntSushi v0.2.0\BurntSushiBlocker_x86.dll'
[DEBUG] Found blocker at '%APPDATA%\Local\OpenByteDev\BurntSushi v0.2.0\BurntSushiBlocker_x86.dll'
[INFO] Injecting blocker...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RemoteIo(Os { code: 193, kind: Uncategorized, message: "%1 is not a valid Win32 application." })', src\blocker.rs:129:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

EOF

**Comment by jhung-dev** [comment] 2023-07-17 05:07
---update: setting %RUST_BACKTRACE% to full and rerunning burnt-sushi---

stack backtrace:
   0:     0x7ff65e0086a3 - <unknown>
   1:     0x7ff65ddd2a2b - <unknown>
   2:     0x7ff65dfe6e41 - <unknown>
   3:     0x7ff65e00a22b - <unknown>
   4:     0x7ff65e009e07 - <unknown>
   5:     0x7ff65e00aced - <unknown>
   6:     0x7ff65e00a786 - <unknown>
   7:     0x7ff65e00a6cf - <unknown>
   8:     0x7ff65e00a6a4 - <unknown>
   9:     0x7ff65e09d6b5 - <unknown>
  10:     0x7ff65e09db56 - <unknown>
  11:     0x7ff65dcae889 - <unknown>
  12:     0x7ff65dca4911 - <unknown>
  13:     0x7ff65dc6bfa1 - <unknown>
  14:     0x7ff65dd4d943 - <unknown>
  15:     0x7ff65dce2cb5 - <unknown>
  16:     0x7ff65dcf0736 - <unknown>
  17:     0x7ff65dce073f - <unknown>
  18:     0x7ff65e096ac4 - <unknown>
  19:     0x7ff9c72326ad - BaseThreadInitThunk
  20:     0x7ff9c926aa68 - RtlUserThreadStart

EOF

will have to comb through the actual source code and see if i can make a PR, but busy right now

**Comment by OpenByteDev** [comment] 2023-07-29 18:02
Duplicate of #9

**Closed as completed by OpenByteDev** 2023-07-29 18:02 UTC
